[project]
name = "browser-use-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.11.9",
    "langchain-openai>=1.1.9",
]
